import { Metadata } from "next";
export const metadata: Metadata = {
  title: "about page",
  description: "Generated by Hamzi",
};

export default function About() {
  return <h1> Abot page here</h1>;
}
