import { Metadata } from "next";
export const metadata: Metadata = {
  // absolete: "by hamza", we don't need to define absolute in layout file, we create absolute in seperate file
  title: "about page",
  description: "Generated by Hamzi",
};

export default function About() {
  return <h1> Abot page here</h1>;
}
