import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Default page",
    template: "%s |hamzi",
    // titleTemplate: "%s | My Next.js App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <p className="p-8 bg-sky-300 font-[700] text-center">
            This is a header
          </p> 
        </header>
        {children}
        <footer>
          <p className="p-8 bg-green-300 font-[700] text-center">
            This is a footer
          </p>
        </footer>
      </body>
    </html>
  );
}
